# FROM node:15.11.0-buster
FROM node@sha256:bbb082a223035cee9f7a6a60154ad4d98e15d417ba89f16f81e2ae15fb70ad4d

RUN apt update && \
  apt install -y --no-install-recommends \
  curl \
  tini && \
  apt clean && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ENV NUXT_HOST 0.0.0.0
ENV NUXT_PORT 1121

EXPOSE 1121

ENTRYPOINT ["tini", "--"]
CMD ["sleep", "infinity"]
