/* eslint-disable no-use-before-define */
/* eslint-disable camelcase */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/service-info': {
    /** May include information related (but not limited to) the workflow descriptor formats, versions supported, the WES API versions supported, and information about general service availability. */
    get: operations['GetServiceInfo']
  }
  '/executable-workflows': {
    /** Returns a list of all executable workflows. */
    get: operations['GetExecutableWorkflows']
  }
  '/parse-workflow': {
    /** The endpoint for parsing the workflow document. */
    post: operations['ParseWorkflow']
  }
  '/runs': {
    /** This list should be provided in a stable ordering. (The actual order is implementation-dependent.) When paging through the list, the client should not make assumptions about live updates but should assume the list's contents reflect the workflow list when the first page is requested. To monitor a specific workflow run, use `GetRunStatus` or `GetRunLog`. */
    get: operations['GetRunsList']
    /** This endpoint creates a new workflow run and returns a `RunId` to monitor its progress. */
    post: operations['RunWorkflow']
  }
  '/runs/{run_id}': {
    /** This endpoint provides detailed information about a given workflow run. The returned result has information about the outputs produced by this workflow (if available), a log object which allows the stderr and stdout to be retrieved, a log array so stderr/stdout for individual tasks can be retrieved, and the overall state of the workflow run (e.g. `RUNNING`, see the State section). */
    get: operations['GetRunLog']
  }
  '/runs/{run_id}/cancel': {
    post: operations['CancelRun']
  }
  '/runs/{run_id}/status': {
    /** This provides an abbreviated (and likely fast depending on implementation) status of the running workflow, returning a simple result with the overall state of the workflow run (e.g. `RUNNING`, see the `State` section). */
    get: operations['GetRunStatus']
  }
  '/runs/{run_id}/data/{path-to-file-or-dir}': {
    /**
     * This provides a remote url to download a file or directory under the `run_dir` of the sapporo-service.
     * - In the case of `path/to/file`, this returns the download link for the file.
     * - In the case of `path/to/dir`, this returns the list of files under the directory in JSON format.
     * - In the case of `path/to/dir?download=true`, this returns the download link of the directory in zip format.
     * The path is relative to the base directory of each run. See `README.md` in the sapporo-service for the structure of `run_dir`. For example, if you want to download the output `foo.txt`, specify something like `outputs/foo.txt`.
     * `..` will be ignored.
     */
    get: operations['GetData']
  }
}

export interface components {
  schemas: {
    /** The workflow type */
    WorkflowTypes: ('CWL' | 'WDL' | 'SMK' | 'NFL') | null
    /** A message that allows one to describe default parameters for a workflow engine. */
    DefaultWorkflowEngineParameter: {
      /** The name of the parameter */
      name: string
      /** Describes the type of the parameter, e.g., float. */
      type: string
      /** The stringified version of the default parameter. e.g. 2.45. */
      default_value: string
    }
    /** The logs, and other key info like timing and exit code, for the overall run of this workflow. */
    Log: {
      /** The task or workflow name */
      name: string
      /** The command line that was executed */
      cmd: string[]
      /** When the command started executing, in ISO 8601 format `%Y-%m-%dT%H:%M:%SZ` */
      start_time: string | null
      /** When the command stopped executing (completed, failed, or canceled), in ISO 8601 format `%Y-%m-%dT%H:%M:%SZ` */
      end_time: string | null
      /** A URL to retrieve standard output logs of the workflow run or task. This URL may change between status requests or be unavailable until the task or workflow has finished execution. It should be available using the same credentials used to access the WES endpoint. */
      stdout: string | null
      /** A URL to retrieve standard error logs of the workflow run or task. This URL may change between status requests or be unavailable until the task or workflow has finished execution. It should be available using the same credentials used to access the WES endpoint. */
      stderr: string | null
      /** Exit code of the program */
      exit_code: number | null
    }
    /** A message containing helpful information about the running service, including supported versions and default settings. */
    ServiceInfo: {
      /** A map with keys as the workflow format type name (currently only CWL and WDL are used although service may support others) and value is a workflow_type_version object which contains an array of one or more version strings */
      workflow_type_versions: {
        CWL?: components['schemas']['WorkflowTypeVersion']
        WDL?: components['schemas']['WorkflowTypeVersion']
        SMK?: components['schemas']['WorkflowTypeVersion']
        NFL?: components['schemas']['WorkflowTypeVersion']
      }
      /** The version(s) of the WES schema supported by this service */
      supported_wes_versions: string[]
      /** The filesystem protocols supported by this service, currently these may include common protocols using the terms 'http', 'https', 'sftp', 's3', 'gs', 'file', or 'synapse', but others are possible and the terms beyond these core protocols are currently not fixed. This section reports those protocols (either common or not) supported by this WES service. */
      supported_filesystem_protocols: string[]
      /** The engine(s) used by this WES service, the key is engine name (e.g., Cromwell), and value is version */
      workflow_engine_versions: { [key: string]: string }
      /** Each workflow engine can present additional parameters that can be sent to the workflow engine. This message will list the default values and their types for each workflow engine. */
      default_workflow_engine_parameters: {
        [key: string]: components['schemas']['DefaultWorkflowEngineParameter'][]
      }
      /** The system statistics, the key is the statistic, the value is the count of runs in that state. See the State enum for the possible keys. */
      system_state_counts: { [key: string]: number }
      /** A web page URL with human-readable instructions on how to get an authorization token for use with a specific WES endpoint. */
      auth_instructions_url: string
      /** An email address URL (mailto:) or web page URL with contact information for a specific WES endpoint operator. Users of the endpoint should use this to report problems or security vulnerabilities. */
      contact_info_url: string
      /** A key-value map of arbitrary extended metadata outside the scope of the above but useful to report back */
      tags: { [key: string]: string }
    } & { [key: string]: unknown }
    ParseRequest: {
      /** The workflow content to be parsed */
      workflow_content?: string | null
      /** The location of the workflow content */
      workflow_location?: string | null
      /** The types of parsing to perform */
      types_of_parsing?:
        | (
            | 'workflow_type'
            | 'workflow_type_version'
            | 'inputs'
            | 'make_template'
          )[]
        | null
    }
    ParseResult: {
      workflow_type: components['schemas']['WorkflowTypes']
      /** The workflow type version */
      workflow_type_version: string | null
      /** The inputs to the workflow */
      inputs: (components['schemas']['WorkflowInput'][] | string) | null
    }
    WorkflowInput: {
      /** The default value for the input */
      default?: (string | number | boolean) | null
      /** The documentation for the input */
      doc?: string | null
      /** The id of the input */
      id?: string
      /** The label for the input */
      label?: string | null
      /** The type of the input */
      type?: 'File' | 'Directory' | 'Any' | 'string' | 'int' | 'boolean'
      /** Whether the input is an array */
      array?: boolean
      /** Whether the input is required */
      required?: boolean
      secondaryFiles?:
        | {
            /** Whether the secondary file is required */
            required: boolean
            /** The pattern for the secondary file */
            pattern: string
          }[]
        | null
    } & { [key: string]: unknown }
    /**
     * - UNKNOWN: The state of the task is unknown. This provides a safe default for messages where this field is missing. For example, a missing field does not accidentally imply that the state is QUEUED.
     * - QUEUED: The task is queued.
     * - INITIALIZING: The task has been assigned to a worker and is currently preparing to run. For example, the worker may be turning on, downloading input files, etc.
     * - RUNNING: The task is running. Input files are downloaded, and the first executor has been started.
     * - PAUSED: The task is paused. An implementation may have the ability to pause a task, but this is not required.
     * - COMPLETE: The task has been completed running. Executors have exited without error, and output files have been successfully uploaded.
     * - EXECUTOR_ERROR: The task encountered an error in one of the Executor processes. Generally, this means that an Executor exited with a non-zero exit code.
     * - SYSTEM_ERROR: The task was stopped due to a system error, but not from an Executor; for example, an upload failed due to network issues, the workers ran out of disk space, etc.
     * - CANCELED: The task was canceled by the user.
     * - CANCELING: The task was canceled by the user and is in the process of stopping.
     */
    State:
      | 'UNKNOWN'
      | 'QUEUED'
      | 'INITIALIZING'
      | 'RUNNING'
      | 'PAUSED'
      | 'COMPLETE'
      | 'EXECUTOR_ERROR'
      | 'SYSTEM_ERROR'
      | 'CANCELED'
      | 'CANCELING'
    /** The service will return a RunListResponse when receiving a successful RunListRequest. */
    RunListResponse: {
      /** A list of workflow runs that the service has executed or is executing. The list is filtered to only include runs that the caller has permission to see. */
      runs: components['schemas']['RunStatus'][]
      /** A token may be supplied as `page_token` in the workflow run list request to get the next page of results. An empty string indicates there are no more items to return. */
      next_page_token?: string
    }
    RunLog: {
      /** workflow run ID */
      run_id: string
      request: components['schemas']['RunRequest']
      state: components['schemas']['State']
      run_log: components['schemas']['Log']
      /** The logs, and other key info like timing and exit code, for each step in the workflow run. */
      task_logs: components['schemas']['Log'][] | null
      /** The outputs from the workflow run. */
      outputs: components['schemas']['AttachedFile'][]
    }
    /** To execute a workflow, send a run request including all the details needed to begin downloading and managing a given workflow. */
    RunRequest: {
      /** The `workflow_params` JSON object specifies input parameters, such as input files. The exact format of the JSON object depends on the conventions of the workflow language being used. Input files should either be absolute URLs or relative URLs corresponding to files uploaded using `workflow_attachment`. The WES endpoint must understand and be able to access URLs supplied in the input. This is implementation-specific. */
      workflow_params?: string | null
      /** The `workflow_type` is the type of workflow language. */
      workflow_type?: string | null
      /** The `workflow_type_version` is the version of the workflow language submitted and must be one supported by this WES instance. */
      workflow_type_version?: string | null
      /** A key-value map of arbitrary metadata outside the scope of `workflow_params` but useful to track with this run request */
      tags?: string | null
      /** Specify the name of the workflow engine to run a workflow. */
      workflow_engine_name: string
      /** Additional parameters can be sent to the workflow engine using this field. Default values for these parameters can be obtained using the `GetServiceInfo` endpoint. */
      workflow_engine_parameters?: string | null
      /** The workflow CWL or WDL document. When `workflow_attachment` is used to attach files, the `workflow_url` may be a relative path to one of the attachments. */
      workflow_url?: string | null
      /** The `workflow_name` is used to execute the workflow registered in the sapporo-service. Please request to `GetServiceInfo` to check registered workflows. If `workflow_name` is specified, `workflow_url`, `workflow_type` and `workflow_type_version` will be ignored. */
      workflow_name?: string | null
      /**
       * The `workflow_attachment` array may be used to upload files required to execute the workflow, including the primary workflow, tools imported by the workflow, other files referenced by the workflow, or files that are part of the input. The implementation should stage these files to a temporary directory and execute the workflow from there. These parts must have a Content-Disposition header with a "filename" provided for each part. Filenames may include subdirectories but must not include references to parent directories with '..' -- implementations should guard against maliciously constructed filenames.
       * As a workflow attachment, it returns a list of files attached to the run request. The file_url is generated by using the file distribution feature of the sapporo-service server.
       * A JSON encoded string from `List[AttachedFile]`. The sapporo-service will download the file to the execution directory.
       */
      workflow_attachment?: (Partial<string[]> & Partial<string>) | null
    }
    RunId: {
      /** workflow run ID */
      run_id: string
    }
    /** Small description of a workflow run, returned by server during listing */
    RunStatus: {
      run_id: string
      state: components['schemas']['State']
    }
    /** Available workflow types supported by a given instance of the service. */
    WorkflowTypeVersion: {
      /** an array of one or more acceptable types for the `workflow_type` */
      workflow_type_version: string[]
    }
    /** An object that can optionally include information about the error. */
    ErrorResponse: {
      /** A detailed error message. */
      msg: string
      /** The integer representing the HTTP status code (e.g. 200, 404). */
      status_code: number
    }
    /** The information about the workflow is provided by `GetServiceInfo` in the mode of executing only the workflow registered by the administrator. */
    Workflow: {
      /** The workflow name */
      workflow_name: string
      /** The workflow document */
      workflow_url: string
      /** The workflow descriptor type must be "CWL" or "WDL" currently (or another alternative supported by this WES instance) */
      workflow_type: string
      /** A map with keys as the workflow format type name (currently only CWL and WDL are used although service may support others) and value is a workflow_type_version object which contains an array of one or more version strings */
      workflow_type_version: string
      /** The workflow_attachment array may be used to download files required to execute the workflow, including the primary workflow, tools imported by the workflow, other files referenced by the workflow, or files that are part of the input. The implementation should stage these files to a temporary directory and execute the workflow from there. */
      workflow_attachment: components['schemas']['AttachedFile'][]
    }
    AttachedFile: {
      /** File name. It can be also specified like `dir_name/file_name`. */
      file_name: string
      /** Remote file URL. */
      file_url: string
    }
  }
}

export interface operations {
  /** May include information related (but not limited to) the workflow descriptor formats, versions supported, the WES API versions supported, and information about general service availability. */
  GetServiceInfo: {
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': components['schemas']['ServiceInfo']
        }
      }
      /** Bad Request */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Internal Server Error */
      500: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** Returns a list of all executable workflows. */
  GetExecutableWorkflows: {
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': components['schemas']['Workflow'][]
        }
      }
      /** Bad Request */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Internal Server Error */
      500: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** The endpoint for parsing the workflow document. */
  ParseWorkflow: {
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': components['schemas']['ParseResult']
        }
      }
      /** Bad Request */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Internal Server Error */
      500: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['ParseRequest']
      }
    }
  }
  /** This list should be provided in a stable ordering. (The actual order is implementation-dependent.) When paging through the list, the client should not make assumptions about live updates but should assume the list's contents reflect the workflow list when the first page is requested. To monitor a specific workflow run, use `GetRunStatus` or `GetRunLog`. */
  GetRunsList: {
    parameters: {
      query: {
        /** The preferred number of workflow runs to return in a page. If not provided, the implementation should use a default page size. The implementation must not return more items than `page_size`, but it may return fewer. Clients should not assume that all items have been returned if fewer than `page_size` items are returned. The value of `next_page_token` indicates the availability of additional pages in the response. */
        page_size?: number
        /** Token to use to indicate where to start getting results. If unspecified, return the first page of results. */
        page_token?: string
      }
    }
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': components['schemas']['RunListResponse']
        }
      }
      /** Bad Request */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Internal Server Error */
      500: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** This endpoint creates a new workflow run and returns a `RunId` to monitor its progress. */
  RunWorkflow: {
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': components['schemas']['RunId']
        }
      }
      /** Bad Request */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Internal Server Error */
      500: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['RunRequest']
      }
    }
  }
  /** This endpoint provides detailed information about a given workflow run. The returned result has information about the outputs produced by this workflow (if available), a log object which allows the stderr and stdout to be retrieved, a log array so stderr/stdout for individual tasks can be retrieved, and the overall state of the workflow run (e.g. `RUNNING`, see the State section). */
  GetRunLog: {
    parameters: {
      path: {
        run_id: string
      }
    }
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': components['schemas']['RunLog']
        }
      }
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** The requested workflow run was not found. */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Internal Server Error */
      500: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  CancelRun: {
    parameters: {
      path: {
        run_id: string
      }
    }
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': components['schemas']['RunId']
        }
      }
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** The requested workflow run wasn't found. */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Internal Server Error */
      500: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** This provides an abbreviated (and likely fast depending on implementation) status of the running workflow, returning a simple result with the overall state of the workflow run (e.g. `RUNNING`, see the `State` section). */
  GetRunStatus: {
    parameters: {
      path: {
        run_id: string
      }
    }
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': components['schemas']['RunStatus']
        }
      }
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** The requested workflow run wasn't found. */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Internal Server Error */
      500: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /**
   * This provides a remote url to download a file or directory under the `run_dir` of the sapporo-service.
   * - In the case of `path/to/file`, this returns the download link for the file.
   * - In the case of `path/to/dir`, this returns the list of files under the directory in JSON format.
   * - In the case of `path/to/dir?download=true`, this returns the download link of the directory in zip format.
   * The path is relative to the base directory of each run. See `README.md` in the sapporo-service for the structure of `run_dir`. For example, if you want to download the output `foo.txt`, specify something like `outputs/foo.txt`.
   * `..` will be ignored.
   */
  GetData: {
    parameters: {
      path: {
        run_id: string
        'path-to-file-or-dir': string
      }
      query: {
        download?: boolean
      }
    }
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': string
        }
      }
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** The requested workflow run wasn't found. */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Internal Server Error */
      500: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
}
